### ISSUE TITLE
Uberdog doesn't work

### ISSUE THREAD

**Issue by toonninja66** [ToontownGalaxy/modern-anesidora#4]
[toontownD-dev.log](https://github.com/ToontownGalaxy/modern-anesidora/files/5744081/toontownD-dev.log)

**Comment by DarthNihilus1** [comment]
Make sure you are running a MySQL server as you need it for the uberdog(database related items )

**Comment by toonninja66** [comment]
And how would I do that?

**Comment by DarthNihilus1** [comment]
https://www.youtube.com/watch?v=OM4aZJW_Ojs
